#!/bin/bash
cd /Users/dirk-jan/repositories/s3/animalshelter-1/docker/jenkins
docker run -p 8080:8080 -p 50000:50000 -v /Users/dirk-jan/repositories/s3/animalshelter-1/docker/jenkins/jenkins_home/:/var/jenkins_home/ jenkins/jenkins:lts
